language: python
sudo: false
python:
  - "3.6"
  - "2.7"
branches:
  only:
    - master
env:
  global:
    - PACKAGENAME="ifconfigparser"
before_install:
  - export PYTHONPATH=$PYTHONPATH:${pwd}:$(pwd)/ifconfigparser:$(pwd)/ifconfigparser/tests
install:
  - pip freeze
script:
  - python -m unittest -v unittest_ifconfig_parser.TestIfconfigParser