language: python
python:
  - "3.6"
  - "2.7"
before_install:
  - export PYTHONPATH=$PYTHONPATH:${pwd}:$(pwd)/ifconfig-parser:$(pwd)/tests
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v unittest_ifconfig_parser.TestIfconfigParser