language: python
python:
  - "3.6"
  - "2.7"
install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/ifconfig-parser:$(pwd)/tests
  - pip install -r requirements.txt
script:
  - python -m unittest unittest_ifconfig_parser.TestIfconfigParser
after_success:
  coveralls