language: python
sudo: false
python:
  - "3.6"
branches:
  only:
    - master
env:
  global:
    - PACKAGENAME="ifconfig-parser"
before_install:
  - export PYTHONPATH=$PYTHONPATH:${pwd}:$(pwd)/ifconfig-parser:$(pwd)/ifconfig-parser/tests
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v unittest_ifconfig_parser.TestIfconfigParser