language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - export PATH=$PATH:$PWD/ifconfig-parser/:$PWD/tests
script:
  - python -m unittest unittest_ifconfig_parser.TestIfconfigParser